FROM docker.io/haskell:9.8.1

WORKDIR "/build"

RUN \
    --mount=type=bind,src=.,dst=.,rw=true \
    --mount=type=cache,target=/root/.stack \
    stack build --system-ghc --copy-bins --local-bin-path /shadow_api

WORKDIR "/shadow_api"

COPY static static

EXPOSE 8080

CMD ["./shadowApiServer"]
